SELECT * FROM TABELA_1;
SELECT * FROM TABELA_2;
SELECT * FROM TABELA_3;

CREATE TABLE TABELA_1
(
    cd_prod NUMBER(6) PRIMARY KEY,
    ds_prod VARCHAR2(100)
);

CREATE TABLE TABELA_2
(
    cd_prod NUMBER(6) PRIMARY KEY,
    ds_prod VARCHAR2(100)
);

CREATE TABLE TABELA_3
(
    cd_prod NUMBER(6) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ds_prod VARCHAR2(100)
);

INSERT INTO TABELA_1 VALUES (1, 'Café');
INSERT INTO TABELA_1 VALUES (2, 'Água');
INSERT INTO TABELA_1 VALUES (3, 'Carvão');
INSERT INTO TABELA_1 VALUES (4, 'Papel Higiênico');

INSERT INTO TABELA_2 VALUES (1, 'Café');
INSERT INTO TABELA_2 VALUES (2, 'Peixe');
INSERT INTO TABELA_2 VALUES (3, 'Papel Higiênico');
INSERT INTO TABELA_2 VALUES (4, 'Refrigerante');
INSERT INTO TABELA_2 VALUES (5, 'Arroz');

SET SERVEROUTPUT ON
SET VERIFY OFF

DECLARE
    CURSOR c_tab_1 IS SELECT cd_prod, ds_prod FROM TABELA_1;
    CURSOR c_tab_2 IS SELECT cd_prod, ds_prod FROM TABELA_2;
    v_has_redundancy NUMBER(1);
    
    BEGIN
        FOR v_tab_1 IN c_tab_1 LOOP
            v_has_redundancy := 0;
            FOR v_tab_2 IN c_tab_2 LOOP
                IF v_tab_1.ds_prod = v_tab_2.ds_prod THEN
                    v_has_redundancy := 1;
                END IF;
            END LOOP;
            IF v_has_redundancy = 0 THEN
                INSERT INTO TABELA_3 (ds_prod) VALUES (v_tab_1.ds_prod);
            END IF;
        END LOOP;
        
        FOR v_tab_2 IN c_tab_2 LOOP
            v_has_redundancy := 0;
            FOR v_tab_1 IN c_tab_1 LOOP
                IF v_tab_2.ds_prod = v_tab_1.ds_prod THEN
                    v_has_redundancy := 1;
                END IF;
            END LOOP;
            IF v_has_redundancy = 0 THEN
                INSERT INTO TABELA_3 (ds_prod) VALUES (v_tab_2.ds_prod);
            END IF;
        END LOOP;
    END;
        