SET VERIFY OFF
SET SERVEROUTPUT ON;

//EXEMPLOS - ESTRUTURAS DE REPETIÇÃO
//LOOP
DECLARE
    V_CONTADOR NUMBER(2):= 1;
    BEGIN
        LOOP
            DBMS_OUTPUT.PUT_LINE(V_CONTADOR);
            V_CONTADOR := V_CONTADOR + 1;
            EXIT WHEN V_CONTADOR > 20;
        END LOOP;
    END;
    
//WHILE
DECLARE
    V_CONTADOR NUMBER(2):= 1;
    BEGIN
        WHILE V_CONTADOR <= 20 LOOP
            DBMS_OUTPUT.PUT_LINE(V_CONTADOR);
            V_CONTADOR := V_CONTADOR + 1;
        END LOOP;
    END;
    
//FOR
BEGIN
    FOR V_CONTADOR IN 1..20 LOOP
        DBMS_OUTPUT.PUT_LINE(V_CONTADOR);
    END LOOP;
END;

//FOR - REVERSE
BEGIN
    FOR V_CONTADOR IN REVERSE 1..20 LOOP
        DBMS_OUTPUT.PUT_LINE(V_CONTADOR);
    END LOOP;
END;